htyf/htyf/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('main.urls', namespace = 'main')),

    url(r'^admin/', include(admin.site.urls)),
)

htyf/main/urls.py
from django.conf.urls import patterns, include, url

from main.views import *

urlpatterns = patterns('',
    url(r'^$', main, name="main"),
    url(r'^history', history, name="history"),
    url(r'^login/', login, name="login"),
    url(r'^logout/', logout, name="logout"),
    url(r'^post/', post, name="post"),
    url(r'^shortestpath/', shortestpath, name="shortestpath"),
    url(r'^like/(?P<post_id>\d+)/', like, name="like"),
    url(r'^unlike/(?P<post_id>\d+)/', unlike, name="unlike"),
    url(r'^delete_post/(?P<post_id>\d+)/', delete_post, name="delete_post"),
    url(r'^path/(?P<start_id>\d+)/', bestpath, name="path"),
    url(r'^locations/', locations, name="locations")
    )

htyf/main/models.py
from django.db import models
from django.contrib.auth.models import User

class Location(models.Model):
    longitude   = models.FloatField()
    latitude    = models.FloatField()
    address     = models.TextField()

class Post(models.Model):
    user        = models.ForeignKey(User)
    location    = models.ForeignKey(Location, null = True)
    text        = models.TextField()
    date        = models.DateTimeField()
    likes       = models.ManyToManyField(User, related_name = "liked")

htyf/main/views.py
import json
from django.contrib                 import auth
from django.shortcuts               import render, redirect
from django.contrib.auth.decorators import login_required
from django.http                    import HttpResponse
from django.contrib.auth.models     import User
from datetime                       import datetime

from main.models                    import *
from main                           import path

def login(request):
    if ('username' in request.POST and 'password' in request.POST):  
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username = username, password = password)
        print user
    else:
        user = None
    
    if (user is None):
        return render(request, "main/login.html")
    else:
        auth.login(request, user)
        return redirect("main:main")

@login_required
def main(request):
    allposts = Post.objects.all()
    
    context = {
        "allposts" : allposts
    }
    return render(request, "main/main.html", context)
    
@login_required
def history(request):
    allposts = Post.objects.all()
    
    context = {
        "allposts" : allposts
    }
    return render(request, "main/history.html", context)
    
@login_required
def shortestpath(request):
    alllocations = Location.objects.all()
    
    if (request.method == "POST"):
        start = Location.objects.get(id = request.POST["start"])
        shortpath = path.shortest(start, "road")
    else:
        shortpath = None
    
    context = {
        "alllocations" : alllocations,
        "path": shortpath
    }
    return render(request, "main/shortestpath.html", context)
    
@login_required
def logout(request):
    auth.logout(request)
    return redirect("main:main")
    
@login_required
def post(request):
    if (request.method == "POST" and request.POST["text"]):
        if ("longitude" in request.POST and request.POST["longitude"]
        and "latitude" in request.POST and  request.POST["latitude"]):
            location = Location(longitude = request.POST["longitude"], latitude = request.POST["latitude"])
            
            if ("address" in request.POST):
                location.address = request.POST["address"]
            location.save()
        else:
            location = None
            
        post = Post(user = request.user, location = location, text = request.POST['text'], date = datetime.now())
        post.save()

    return redirect("main:main")
    
@login_required
def like(request, post_id):
    post = Post.objects.get(id = post_id)
    post.likes.add(request.user)
    print post.likes
    return redirect("main:main")
    
@login_required
def unlike(request, post_id):
    post = Post.objects.get(id = post_id)
    post.likes.remove(request.user)
    return redirect("main:main")
    
@login_required
def delete_post(request, post_id):
    post = Post.objects.get(id = post_id)
    if (post.user == request.user):
        post.location.delete()
        post.delete()
    
    return redirect("main:main")
    
def bestpath(request, start_id):
    start = Location.objects.get(id = start_id)
    shortpath = path.shortest(start, "road")
    return HttpResponse(json.dumps(shortpath), content_type="application/json")
    
@login_required
def locations(request):
    posts = Post.objects.filter(user = request.user)
    
    locations = []
    for post in posts:
        locations.append({
            "longitude": post.location.longitude, 
            "latitude": post.location.latitude, 
            "address": post.location.address
        })
        
    return HttpResponse(json.dumps(locations), content_type="application/json")

htyf/main/templates/main/base.html
{% load staticfiles %}

{% block head %}
<!DOCTYPE html>
<html>
    <head>
        <title>Welcome {{ user.username }}|| Get the travelling news feed from the people you are connected</title>
    </head>
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/user.css' %}">
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true"></script>
    <link href='http://fonts.googleapis.com/css?family=Raleway:700,800,400' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <body {% block body_attrs %}{% endblock %}>
        <div id="header">Traveller Space</div>
        <div id="content">
            <div id="menu">
                <ul>
	                <li><a>Hello {{ user.username }}</a></li>
	                <li><a href="{% url 'main:main' %}"/>feed page</a></li>
	                <li><a href="{% url 'main:history' %}">visit history</a></li>
	                <li><a href="{% url 'main:shortestpath' %}">shortest path</a></li>
	                <li><a href="{% url 'main:logout' %}">log out</a></li>
                </ul>	
		
            </div>
        
{% endblock %}

{% block content %}{% endblock %}

{% block foot %}
    </div>
    
    <script src="{% static 'main/javascript/webscript.js' %}"></script>

    <div id="footer">&copy;Website name</div>

    </body>
</html>
{% endblock %}

htyf/main/templates/main/history.html
{% extends 'main/base.html' %}

{% block body_attrs %}onload="showMeMap()"{% endblock %}

{% block content %}
    <div id="feedBox">
        <h4>My Travel History</h4>
        <!--HERE WE CAN LOAD ALL THE HISTORY OF THE VISITED PLACES-->
        
        <h5 onclick="showMeUpdates()">Change View</h5>
        <div id="mapLoad" ></div>
        <div id="feedwrapper">
            {% for post in allposts %}
                <div class="feedstyle">
                    <div class="personName">{{ user.username }}</div>
                    <div class="datestyle">{{ post.date|date:"F j" }}</div>
                    <div class="deleteme" post-id="{{ post.id }}">delete</div>
                    {{ post.content }}
                    <div class="mapSpace"></div>
                    
                    <address>
                    <b>Posted at </b>: {{ post.location.address }}
                    </address>
                    
                    {% if user in post.likes.all %}
                        <a href="{% url 'main:unlike' post.id %}"><div class="likeSpace">Unlike</div></a>
                    {% else %}
                        <a href="{% url 'main:like' post.id %}"><div class="likeSpace">Like</div></a>
                    {% endif %}
                    <div class="loadLikes">{{ post.likes.count }} likes</div>
                </div>
            {% endfor %}
        </div>
	
        <!-- ########################### -->

    </div>
{% endblock %}

htyf/main/templates/main/login.html
<!DOCTYPE html>
<html>
<head>
{% load staticfiles %}
<title>Welcome to the website</title>
</head>
<link rel="stylesheet" type="text/css" href="{% static 'main/css/main.css' %}">
<link href='http://fonts.googleapis.com/css?family=Raleway:700,800,400' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Roboto:400,100,300' rel='stylesheet' type='text/css'>
<body>
<div id="header">
Personal Travelling Timetable</div>
<div id="logo_holder">
<img src="{%static 'main/images/logo.png' %}" width="100" height="100"><br>Welcome to your personal timetable
<br>Record your All important information in easy and simple way
</div>	
<div id="content">
<div id="form_holder">
<form action="{% url 'main:login' %}" method="POST">
{% csrf_token %}
<label class="title">Username</label><input type="text" name="username" class="form_input"/><br><br>
<label class="title">Password</label><input type="password" name="password" class="form_input"/><br><br>
<input type="submit" value="Log in" class="button_design">
</form>

</div>

</div>

<div id="footer">
&copy;Website name</div>

</body>
</html>

htyf/main/templates/main/main.html
{% extends 'main/base.html' %}

{% block body_attrs %}onload="loadFirst()"{% endblock %}

{% block content %}
    <div id="feed">	
        <div id="updateBox">
            <form id="myForm" onsubmit="checkform()" name="myForm" method="POST" action="{% url 'main:post' %}">
                {% csrf_token %}
                <textarea rows="7" cols="20" placeholder="Whats in your mind" name ="text"></textarea><br>

                <span  class="buttonstyle" onclick="getLocation()" id="loadAutomatically">load address automatically</span>

                <span class="buttonstyle" onclick="showAddBox()">enter address</span><br><br>

                <textarea rows="1" cols="20" placeholder="Enter Address"  id="loadManually"></textarea>
                <br>
                <input type="submit" class="buttonstyle" value="share">		
            </form><br>
            <br><br>
        </div>
        <address id="outputText">
	
        </address>
        <div id="errorMess"></div>	
        <div id="mapload"></div>	

        <h3>What people are saying</h3>

        <div id="feedBox">
            <!--HERE WE CAN LOAD ALL THE FEEDS FROM USERS-->
            {% for post in allposts %}
                <div class="feedstyle">
                    <div class="personName">{{ post.user.username }}</div>
                    <div class="datestyle">{{ post.date|date:"F j" }}</div>
                    {{ post.text }}
                    
                    <div class="mapSpace"></div>
                    
                    {% if user in post.likes.all %}
                        <a href="{% url 'main:unlike' post.id %}"><div class="likeSpace">Unlike</div></a>
                    {% else %}
                        <a href="{% url 'main:like' post.id %}"><div class="likeSpace">Like</div></a>
                    {% endif %}
                    
                    <div class="loadLikes">{{ post.likes.count }} likes</div>
                </div>
	        {% endfor %}
            <!-- ########################### -->

        </div>	
    </div>
{% endblock %}

htyf/main/templates/main/shortestpath.html
{% extends 'main/base.html' %}

{% block content %}

<h3>Calculate the shortest path between two destinations</h3>
<!--HERE WE ARE LOADING MAP WITH ALL THE VISITED LOCATIONS>
<div id="loadMap">


</div>	

<!--HERE WE CAN SHOW THE INPUT FORM, TO ENTER THE DESTINATIONS-->
<div id="calculatePath">
    <form method="POST" action="{% url 'main:shortestpath' %}">
        {% csrf_token %}
        <select  id="sourceAdd" class="selectdesign" name="start">
            {% for location in alllocations %}
                <option value="{{ location.id }}">{{ location.address }}</option>
            {% endfor %}
        </select>
	
        <input type="submit" value="calculate path" onclick="calcRoute()" class="buttonstyle">
    </form>
</div>

{% for loc in path %}

{{ loc.address }}<br />

{% endfor %}

<!--HERE WE CAN SHOW THE SHORTEST PATH RESULT-->
<div id="addressResult">
	
</div>

{% endblock %}